### PR TITLE
refactor: Update headings and body text to use new custom Tailwind classes

### PR DESCRIPTION
**Pull request by hicass**
## Description

This PR introduces the application of the new custom Tailwind CSS classes to the Headings and Body text of the app.

### 1. The following components have the new classes applied to them:
- Button
- Footer
- FooterLink
- AIPowredBadge
- AIPoweredSection
- CheckboxLabel
- DemoSection
- AccordionItem
- FAQSection
- Hero
- StatTag
- NumberIcon
- StepCard
- StepsSection
- NavLink
- profile

### CODE REVIEW

**Comment by bachdumpling** [comment]
LGTM 
However, can you write a short like documentation for the usage of this standardization? For example, 

why would someone use this class instead of just using the font-bold class?

.body-txt-lg-bold {
    @apply font-bold;
  }
  
You should be able to use chatgpt or claude to write documentation pretty efficiently. Just make sure to fact check hallucination and stuffs.

**Comment by hicass** [comment]
Yes! I can write out documentation. Where is the best place to put it? Should I update the PR description and put it in there or somewhere in the notion?

**Comment by bachdumpling** [comment]
The best place would be in the readme file in the /client
you can create a new section called Style Guide 
you can push new changes directly here when you are finished! TY

**Comment by hicass** [comment]
The documentation has been added to the README! :)

**Review by bachdumpling — APPROVED** [review]
LGTM!!

**Pull request merged**
