### PR TITLE
Style: Update Profile Page

### PR DESCRIPTION
**Pull request by hicass**
## Description
This PR updated the styling for the profile page to match the wireframe

Screen Shot 2024-08-12 at 10 16 45 AM

### CODE REVIEW

**Comment by bachdumpling** [comment]
Take a look at some of the changes i made
Now I think is a good time to start using global classnames to standardize the styling on our app

Like using h1 for h1 text instead of text-2xl
and we have to think ahead or perform css refactoring later on

**Comment by bachdumpling** [comment]
If everything looks good, we can merge and start going forward like this

If any of my changes have issues, push your fix and we merge

**Comment by bachdumpling** [comment]
Another benefit of using global classnames is making it easy to resize all of them when its time to make the app responsive for tablets and phones

**Comment by hicass** [comment]
ok! yes this all looks good

**Pull request merged**
